#!/bin/bash

CRON=/etc/crontab
LOG=/home/vagrant/test_cron
MD5=$(md5sum $CRON | cut -d " " -f1)

if [ ! -f $LOG ]; then
    echo $MD5 > $LOG
else
    if [ "$(cat $LOG)" != "$MD5" ]; then
        echo "new"
        echo "Message" | mail -s "Crontab has changed" root
        echo $MD5 > $LOG
    fi
fi
exit

# crontab -e
# 00 00 * * * sh /git/scripts/04
